# Import rpy2

In [1]:
import rpy2

# Install the SpatialQPFs R package from github and its dependencies from CRAN

In [1]:
#from rpy2.robjects.packages import importr
#utils = importr('utils')

# Import remotes package
#remotes = importr('remotes')

# Install the package from GitHub
#remotes.install_github("https://github.com/Genentech/SpatialQPFs", ref = "development")

In [ ]:
# import rpy2's package module
import rpy2.robjects.packages as rpackages

# import R's utility package
utils = rpackages.importr('utils')

# select a mirror for R packages
utils.chooseCRANmirror(ind=70) # select the first mirror in the list

In [ ]:
# R package names
packnames = ('magrittr','dplyr','tidyr','igraph','SpatEntropy',
             'spatstat.geom','spatstat.explore','spatstat.utils', 'ggplot2', 'mclust', 'spdep','sp','gstat','rpart', 
             'FNN', 'boot', 'dbmss', 'ecespa', 'plotly', 'pracma', 'reshape2', 'sf', 'sm', 'splancs','stringr','RTriangle','plyr')

# R vector of strings
from rpy2.robjects.vectors import StrVector

# Selectively install what needs to be install.
# We are fancy, just because we can.
names_to_install = [x for x in packnames if not rpackages.isinstalled(x)]
if len(names_to_install) > 0:
    utils.install_packages(StrVector(names_to_install))

# Test the toy example in the tutorial

In [2]:
import rpy2.robjects as robjects
from rpy2.robjects.packages import importr, data

SpatialQPFs = importr('SpatialQPFs')

## read the build-in toy example data

In [3]:
utils = importr('utils')
top_path = robjects.r('system.file("extdata", "dat.csv", package = "SpatialQPFs")')
dat = utils.read_csv(top_path)

In [4]:
import rpy2.robjects.pandas2ri as pandas2ri
dat = pandas2ri.rpy2py_dataframe(dat)
print(dat)

         x     y cell_id
1     3779  8206      TC
2     2655   470      TC
3     1088  5104  Stroma
4     7313  4994  Stroma
5     8735  7233      TC
...    ...   ...     ...
2796  6058  5728      TC
2797  6455  6267     Lym
2798  8129  6236  Stroma
2799  6100  9583  Stroma
2800   193  5446  Stroma

[2800 rows x 3 columns]

In [5]:
# the first 20 rows
dat.iloc[0:20]

       x     y cell_id
1   3779  8206      TC
2   2655   470      TC
3   1088  5104  Stroma
4   7313  4994  Stroma
5   8735  7233      TC
6   9450  9375  Others
7    597  5852  Stroma
8   2679  4492      TC
9   1786  2610     Lym
10  9792  8173      TC
11  1297  1465     Lym
12  4142  6521      TC
13  2908  1577  Stroma
14  1601  2656     Lym
15  7149  4428      TC
16  1888  2316  Others
17  9471  5543      TC
18  8537  7951  Stroma
19  1252  9848  Others
20  9819  7061      TC

# Start to use the SpatialQPFs

In [6]:
path = robjects.r('gsub("dat.csv", "", system.file("extdata", "dat.csv", package = "SpatialQPFs"))')
file = 'dat.csv'

In [7]:
SpatialQPFs.Data_Vis(path = path, 
                     file = file, 
                     cell_class_var = "cell_id", 
                     x_var = "x", 
                     y_var = "y", 
                     cell_type = "Lym")

R[write to console]: No trace type specified:
  Based on info supplied, a 'scatter3d' trace seems appropriate.
  Read more about this trace type -> https://plotly.com/r/reference/#scatter3d

R[write to console]: No scatter3d mode specifed:
  Setting the mode to markers
  Read more about this attribute -> https://plotly.com/r/reference/#scatter-mode

<rpy2.robjects.vectors.ListVector object at 0x105ce1390> [19]
R classes: ('plotly', 'htmlwidget')
[Lis..., NUL..., NUL..., Lis..., Lis..., NUL..., Sex..., Lis...]
  x: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x311ab5690> [19]
  width: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x1056f8ad0> [0]
  height: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x1056f8ad0> [0]
  sizingPolicy: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x311ab5690> [19]
  dependencies: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x31200c710> [19]
  elementId: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x1056f8ad0> [0]
  preRenderHook: <class 'rpy2.rinterface.SexpClosure'>
  <rpy2.rinterface.SexpClosure object at 0x31200cf90> [3]
  jsHooks: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x31200ce90> [19]

In [9]:
SpatialQPFs.Data_Vis(path = path, 
                     file = file, 
                     cell_class_var = "cell_id", 
                     x_var = "x", 
                     y_var = "y", 
                     cell_type = "TC")

R[write to console]: No trace type specified:
  Based on info supplied, a 'scatter3d' trace seems appropriate.
  Read more about this trace type -> https://plotly.com/r/reference/#scatter3d

R[write to console]: No scatter3d mode specifed:
  Setting the mode to markers
  Read more about this attribute -> https://plotly.com/r/reference/#scatter-mode

<rpy2.robjects.vectors.ListVector object at 0x16a103850> [19]
R classes: ('plotly', 'htmlwidget')
[Lis..., NUL..., NUL..., Lis..., Lis..., NUL..., Sex..., Lis...]
  x: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x16a103650> [19]
  width: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x1036b5890> [0]
  height: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x1036b5890> [0]
  sizingPolicy: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x16a110990> [19]
  dependencies: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x16a110d50> [19]
  elementId: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x1036b5890> [0]
  preRenderHook: <class 'rpy2.rinterface.SexpClosure'>
  <rpy2.rinterface.SexpClosure object at 0x16a111050> [3]
  jsHooks: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x16a111150> [19]

## Point pattern data analysis
To utilize spatial point process methods, SpatialQPFs provides 3 functions:

- for a single cell type, one can use **Point_pattern_data_uni()**
- for a pair of cell types, one can call **Point_pattern_data_bi()** and **Point_pattern_data_ITLR()**.

For details of the functions, refer to **help(Point_pattern_data_uni)**, **help(Point_pattern_data_bi)**, and **help(Point_pattern_data_ITLR)**

In [8]:
ss_point_uni_lym = SpatialQPFs.Point_pattern_data_uni(path = path, 
                                                      file = file, 
                                                      x_var = "x", 
                                                      y_var = "y", 
                                                      cell_class_var = "cell_id", 
                                                      cell_type = "Lym", 
                                                      scale = 500, 
                                                      myplot = True)

In [9]:
print(ss_point_uni_lym)

$g_AUC
[1] 0.004661152

$g_r
[1] 0.05066369

$k_AUC
[1] 0.0003789604

$k_vals_med
       50%
0.00789986

$k_vals_q1
       25%
0.00198158

$k_vals_q3
       75%
0.01722362

$k_vals_max
[1] 0.02926199

$pcf_AUC
[1] 0.1330209

$pcf_vals_med
     50%
3.776434

$pcf_vals_q1
    25%
3.49762

$pcf_vals_q3
     75%
3.913852

$pcf_vals_max
[1] 5.176213

$pcf_vals_min
[1] 3.383061

$pcf_r
[1] 0.00266651

$CE
   naive
0.890238

In [10]:
ss_point_uni_TC = SpatialQPFs.Point_pattern_data_uni(path = path, 
                                                     file = file, 
                                                     x_var = "x", 
                                                     y_var = "y", 
                                                     cell_class_var = "cell_id", 
                                                     cell_type = "TC", 
                                                     scale = 500, 
                                                     myplot = True)

In [11]:
print(ss_point_uni_TC)

$g_AUC
[1] -3.399809e-05

$g_r
[1] 0.04474579

$k_AUC
[1] 7.373894e-06

$k_vals_med
        50%
0.002108313

$k_vals_q1
         25%
0.0005112325

$k_vals_q3
        75%
0.004734315

$k_vals_max
[1] 0.008146708

$pcf_AUC
[1] 0.002099142

$pcf_vals_med
     50%
1.067271

$pcf_vals_q1
      25%
0.9994965

$pcf_vals_q3
    75%
1.08681

$pcf_vals_max
[1] 1.106596

$pcf_vals_min
[1] 0.7911587

$pcf_r
[1] 0.01052842

$CE
   naive
1.008257

In [12]:
ss_point_bi = SpatialQPFs.Point_pattern_data_bi(path = path, 
                                                file = file, x_var = "x", y_var = "y", cell_class_var = "cell_id", 
                                                from_type = "Lym", 
                                                to_type = "TC", 
                                                scale = 500, myplot = True)

Cross type G-function is calculated.
Cross type K-function is calculated.
1,
2.
Differences in Ripley's K-function is calculated.
Pair correlation function is calculated.
Mark correlation function is calculated.Mark connection function is calculated.
Marcon and Puech's M function is calculated.

In [13]:
print(ss_point_bi)

$g_cross_AUC
[1] 0.0006782376

$g_cross_r
[1] 0.03889667

$k_cross_AUC
[1] 2.426612e-05

$k_cross_vals_med
        50%
0.002336459

$k_cross_vals_q1
         25%
0.0005660821

$k_cross_vals_q3
        75%
0.005277495

$k_cross_vals_max
[1] 0.00944047

$K12_Diff_AUC
[1] 0.0003790916

$k_k1k2_vals_med
       50%
0.00594408

$k_k1k2_vals_q1
        25%
0.001634323

$k_k1k2_vals_q3
       75%
0.01270813

$k_k1k2_vals_max
[1] 0.02151166

$K1K12_Diff_AUC
[1] 0.0003633184

$k_k1k12_vals_med
        50%
0.005750551

$k_k1k12_vals_q1
        25%
0.001602771

$k_k1k12_vals_q3
      75%
0.0122064

$k_k1k12_vals_max
[1] 0.02026278

$K2K12_Diff_AUC
[1] -1.577328e-05

$k_k2k12_vals_med
          50%
-0.0001935285

$k_k2k12_vals_q1
          25%
-0.0005017328

$k_k2k12_vals_q3
          75%
-3.155209e-05

$k_k2k12_vals_max
[1] 0

$pcf_AUC
[1] 0.008457301

$pcf_vals_med
    50%
1.21454

$pcf_vals_q1
     25%
1.168805

$pcf_vals_q3
    75%
1.22244

$pcf_vals_max
[1] 1.229431

$pcf_vals_min
[1] 1.091761

$pcf_r
[1] 0.04445334

$mrcf_AUC
[1] 0.01127915

$mrcf_vals_med
     50%
1.228653

$mrcf_vals_q1
    25%
1.20611

$mrcf_vals_q3
     75%
1.274725

$mrcf_vals_max
[1] 1.277776

$mrcf_vals_min
[1] 0.8980466

$mrcf_r
[1] 0.02778333

$mccf_AUC
[1] -0.0003683821

$mccf_vals_med
       50%
0.05376596

$mccf_vals_q1
       25%
0.05269271

$mccf_vals_q3
       75%
0.05565426

$mccf_vals_max
[1] 0.05800203

$mccf_vals_min
[1] 0.04952488

$mccf_r
[1] 0.04445334

$M_AUC
[1] 0.1063055

$M_vals_med
     50%
3.591923

$M_vals_q1
     25%
3.280865

$M_vals_q3
     75%
4.116922

$M_vals_max
[1] 4.611528

$M_vals_min
[1] 0.4818792

$M_r
[1] 0.03334

In [14]:
ss_point_ITLR = SpatialQPFs.Point_pattern_data_ITLR(path = path, 
                                                    file = file, x_var = "x", y_var = "y", cell_class_var = "cell_id", 
                                                    from_type = "Lym", 
                                                    to_type = "TC", 
                                                    micron_per_pixel = 0.5, 
                                                    myplot = True)

Xrange is  1 4998
Yrange is  1 4974
Doing quartic kernel
fitting ...
  |======================================================================| 100%

In [17]:
print(ss_point_ITLR)

$ITLR
[1] 0.09045971

$ITLR2
[1] 0.09256449

## Areal data
To utilize spatial lattice process methods, SpatialQPFs provides **Areal_data()** function. For details of the function, refer to **help(Areal_data)**

In [15]:
ss_lattice_bi = SpatialQPFs.Areal_data(path = path, file = file, 
                                       x_var = "x", y_var = "y", cell_class_var = "cell_id", 
                                       from_type = "Lym", 
                                       to_type = "TC", 
                                       scale = 200, 
                                       myplot = True)

Areal features are calculated.

In [16]:
print(ss_lattice_bi)

$BC
[1] 0.5185003

$MH_index
[1] 0.3257691

$JaccardJ
[1] 0.2122787

$SorensenL
[1] 0.3502143

$Moran_I_tumor
[1] 0.03291831

$Moran_I_immune
[1] 0.6420521

$moran_I_Bivariate
[1] 0.06693746

$geary_TC
[1] 0.9751893

$geary_IC
[1] 0.5006019

$moran_HL_TC
[1] 0.003676471

$moran_HH_TC
[1] 0.02573529

$moran_LH_TC
[1] 0.009191176

$moran_LL_TC
[1] 0.003676471

$geary_HH_TC
[1] 0.02389706

$geary_LL_TC
[1] 0.001838235

$geary_OP_TC
[1] 0.009191176

$geary_NE_TC
[1] 0.007352941

$moran_HL_IC
[1] 0

$moran_HH_IC
[1] 0.07352941

$moran_LH_IC
[1] 0.007352941

$moran_LL_IC
[1] 0

$geary_HH_IC
[1] 0.06433824

$geary_LL_IC
[1] 0

$geary_OP_IC
[1] 0.003676471

$geary_NE_IC
[1] 0

$moran_HH_TC_HH_IC
[1] 0.001102941

$moran_HH_TC_HL_IC
[1] 0

$moran_HH_TC_LH_IC
[1] 0

$moran_HH_TC_LL_IC
[1] 0

$moran_HL_TC_HH_IC
[1] 0

$moran_HL_TC_HL_IC
[1] NA

$moran_HL_TC_LH_IC
[1] 0

$moran_HL_TC_LL_IC
[1] 0

$moran_LH_TC_HH_IC
[1] 0.0003676471

$moran_LH_TC_HL_IC
[1] 0

$moran_LH_TC_LH_IC
[1] 0

$moran_LH_TC_LL_IC
[1] 0

$moran_LL_TC_HH_IC
[1] 0

$moran_LL_TC_HL_IC
[1] NA

$moran_LL_TC_LH_IC
[1] 0

$moran_LL_TC_LL_IC
[1] 0

$geary_HH_TC_HH_IC
[1] 0.005514706

$geary_HH_TC_LL_IC
[1] 0

$geary_HH_TC_OP_IC
[1] 0

$geary_HH_TC_NE_IC
[1] 0

$geary_LL_TC_HH_IC
[1] 0

$geary_LL_TC_LL_IC
[1] 0

$geary_LL_TC_OP_IC
[1] 0

$geary_LL_TC_NE_IC
[1] NA

$geary_OP_TC_HH_IC
[1] 0

$geary_OP_TC_LL_IC
[1] 0

$geary_OP_TC_OP_IC
[1] 0

$geary_OP_TC_NE_IC
[1] 0

$geary_NE_TC_HH_IC
[1] 0

$geary_NE_TC_LL_IC
[1] 0

$geary_NE_TC_OP_IC
[1] 0

$geary_NE_TC_NE_IC
[1] NA

$GetisOrd_HS
[1] 0.009191176

$GetisOrd_CS
[1] 0

$GetisOrd_CS_IC_HS_TC
[1] 0

$GetisOrd_CS_TC_HS_IC
[1] 0

$GetisOrd_HS_IC
[1] 0.07536765

$GetisOrd_CS_IC
[1] 0.005514706

$GetisOrd_HS_TC
[1] 0.04044118

$GetisOrd_CS_TC
[1] 0.01286765

$GetisOrd_S_intra_cancer
[1] 0.9998912

$GetisOrd_S_intra_immune
[1] 0.9998912

$Lee_L
[1] 0.1589278

$Lee_HL_TC_IC
[1] 0.01102941

$Lee_HH_TC_IC
[1] 0.04963235

$Lee_LH_TC_IC
[1] 0.01838235

$Lee_LL_TC_IC
[1] 0.003676471

$Lee_HL_IC_TC
[1] 0.02022059

$Lee_HH_IC_TC
[1] 0.03860294

$Lee_LH_IC_TC
[1] 0.009191176

$Lee_LL_IC_TC
[1] 0.001838235

## Geostatistics data
To utilize geostatistics process methods, SpatialQPFs provides **Geostatistics_data()** function. For details of the function, refer to **help(Geostatistics_data)**

In [17]:
ss_geostat_bi = SpatialQPFs.Geostatistics_data(path = path, file = file, 
                                               x_var = "x", y_var = "y", cell_class_var = "cell_id", 
                                               from_type = "Lym", 
                                               to_type = "TC", 
                                               scale = 500, 
                                               myplot = True)

Geostatistics features are calculated.

In [18]:
print(ss_geostat_bi)

$sill_tumor
[1] 1.22331e-05

$sill_immune
[1] 0.0003285947

$range_tumor
[1] 0.03298128

$range_immune
[1] 0.03490245

$kappa_tumor
[1] 1

$kappa_immune
[1] 5

$sill_IC_TC
[1] 0.0003022043

$range_IC_TC
[1] 0.03243775

$kappa_IC_TC
[1] 5

$sill_TC_IC
[1] 1.153167e-05

$range_TC_IC
[1] 0.01435864

$kappa_TC_IC
[1] 4.2

$kappa_IK
[1] 1

$sill_IK
[1] 0.2637792

$range_IK
[1] 0.1928726

## Graph data

In [21]:
from rpy2.robjects.vectors import StrVector

graph_uni_TC = SpatialQPFs.DT_graph_uni_subregion_random(path = path, file = file, 
                                   x_var = "x", y_var = "y", cell_class_var = "cell_id", 
                                   cell_type = "TC", 
                                   scale = 1000, side_length = 2000, num_FOV = 20, set_seed = 42, myplot = True)

graph_uni_lym = SpatialQPFs.DT_graph_uni_subregion_random(path = path, file = file, 
                                   x_var = "x", y_var = "y", cell_class_var = "cell_id", 
                                   cell_type = "Lym", 
                                   scale = 1000, side_length = 2000, num_FOV = 20, set_seed = 42, myplot = True)

graph_uni_stroma = SpatialQPFs.DT_graph_uni_subregion_random(path = path, file = file, 
                                   x_var = "x", y_var = "y", cell_class_var = "cell_id", 
                                   cell_type = "Stroma", 
                                   scale = 1000, side_length = 2000, num_FOV = 20, set_seed = 42, myplot = True)



graph_all = SpatialQPFs.DT_graph_cross_subregion_random(path = path, file = file, 
                                   x_var = "x", y_var = "y", cell_class_var = "cell_id", 
                                   cell_type = ["TC", "Lym", "Stroma", "Others"], 
                                   scale = 1000, side_length = 2000, num_FOV = 20, set_seed = 42, myplot = True)

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
Processing FOV: 1
Processing FOV: 2
Processing FOV: 3
Processing FOV: 4
Processing FOV: 5
Processing FOV: 6
Processing FOV: 7
Processing FOV: 8
Processing FOV: 9
Processing FOV: 10
Processing FOV: 11
Processing FOV: 12
Processing FOV: 13
Processing FOV: 14
Processing FOV: 15
Processing FOV: 16
Processing FOV: 17
Processing FOV: 18
Processing FOV: 19
Processing FOV: 20

In [22]:
print(graph_uni_TC)

$mean_x_weight
[1] 341.9047

$median_x_weight
[1] 316.3526

$sd_x_weight
[1] 189.5267

$iqr_x_weight
[1] 253.4453

$skewness_x_weight
[1] 0.7379734

$kurtosis_x_weight
[1] 3.078021

$min_x_weight
[1] 46.42725

$max_x_weight
[1] 941.0975

$range_x_weight
[1] 888.2847

$Q10_weight
[1] 129.9211

$Q20_weight
[1] 180.4079

$Q25_weight
[1] 207.8196

$Q30_weight
[1] 232.3328

$Q40_weight
[1] 276.2156

$Q60_weight
[1] 364.2922

$Q70_weight
[1] 423.0589

$Q75_weight
[1] 444.1035

$Q80_weight
[1] 485.7368

$Q90_weight
[1] 598.8658

$theil_index_weight
[1] 0.1876369

$gini_coeff_weight
[1] 0.3007102

$mean_x_closeness
[1] 0.0009336501

$median_x_closeness
[1] 0.0009218071

$sd_x_closeness
[1] 0.0001553146

$iqr_x_closeness
[1] 0.0002475451

$skewness_x_closeness
[1] 0.1378892

$kurtosis_x_closeness
[1] 2.074654

$min_x_closeness
[1] 0.0006501667

$max_x_closeness
[1] 0.001222484

$range_x_closeness
[1] 0.0005822904

$Q10_closeness
[1] 0.000736942

$Q20_closeness
[1] 0.0007896602

$Q25_closeness
[1] 0.0008037539

$Q30_closeness
[1] 0.0008276245

$Q40_closeness
[1] 0.0008790804

$Q60_closeness
[1] 0.0009688396

$Q70_closeness
[1] 0.001035236

$Q75_closeness
[1] 0.001060593

$Q80_closeness
[1] 0.001083414

$Q90_closeness
[1] 0.001155939

$theil_index_closeness
[1] 0.1422839

$gini_coeff_closeness
[1] 0.0938724

$mean_x_betweenness
[1] 0.06023753

$median_x_betweenness
[1] 0.04720288

$sd_x_betweenness
[1] 0.05340788

$iqr_x_betweenness
[1] 0.07404862

$skewness_x_betweenness
[1] 0.8201344

$kurtosis_x_betweenness
[1] 2.842056

$min_x_betweenness
[1] 0

$max_x_betweenness
[1] 0.2013879

$range_x_betweenness
[1] 0.2013879

$Q10_betweenness
[1] 0.0009756387

$Q20_betweenness
[1] 0.01213235

$Q25_betweenness
[1] 0.01654156

$Q30_betweenness
[1] 0.02337255

$Q40_betweenness
[1] 0.03363845

$Q60_betweenness
[1] 0.06376951

$Q70_betweenness
[1] 0.07771271

$Q75_betweenness
[1] 0.09206894

$Q80_betweenness
[1] 0.1045411

$Q90_betweenness
[1] 0.1379019

$theil_index_betweenness
[1] 0.2927516

$gini_coeff_betweenness
[1] 0.483103

$mean_x_degree
[1] 0.1212121

$median_x_degree
[1] 0.1149577

$sd_x_degree
[1] 0.03124014

$iqr_x_degree
[1] 0.04174963

$skewness_x_degree
[1] 0.2111385

$kurtosis_x_degree
[1] 3.022713

$min_x_degree
[1] 0.06122449

$max_x_degree
[1] 0.1905842

$range_x_degree
[1] 0.1306689

$Q10_degree
[1] 0.08792271

$Q20_degree
[1] 0.09529212

$Q25_degree
[1] 0.1028497

$Q30_degree
[1] 0.1111111

$Q40_degree
[1] 0.1149577

$Q60_degree
[1] 0.1237245

$Q70_degree
[1] 0.1379493

$Q75_degree
[1] 0.1395349

$Q80_degree
[1] 0.1395349

$Q90_degree
[1] 0.1609408

$theil_index_degree
[1] 0.09894185

$gini_coeff_degree
[1] 0.1364111

$mean_x_triangle_area
[1] 38044.83

$median_x_triangle_area
[1] 27469.38

$sd_x_triangle_area
[1] 36202.47

$iqr_x_triangle_area
[1] 35823.25

$skewness_x_triangle_area
[1] 1.48537

$kurtosis_x_triangle_area
[1] 5.028701

$min_x_triangle_area
[1] 1807.25

$max_x_triangle_area
[1] 164302

$range_x_triangle_area
[1] 162182.7

$Q10_triangle_area
[1] 7112.375

$Q20_triangle_area
[1] 10863.6

$Q25_triangle_area
[1] 13345.37

$Q30_triangle_area
[1] 15286

$Q40_triangle_area
[1] 20370.55

$Q60_triangle_area
[1] 35461.45

$Q70_triangle_area
[1] 44900.05

$Q75_triangle_area
[1] 51195.44

$Q80_triangle_area
[1] 59217.7

$Q90_triangle_area
[1] 90076.45

$theil_index_triangle_area
[1] 0.3679089

$gini_coeff_triangle_area
[1] 0.4452052

$mean_x_triangle_perimeter
[1] 998.2516

$median_x_triangle_perimeter
[1] 957.7757

$sd_x_triangle_perimeter
[1] 398.0856

$iqr_x_triangle_perimeter
[1] 540.3606

$skewness_x_triangle_perimeter
[1] 0.4805242

$kurtosis_x_triangle_perimeter
[1] 2.584347

$min_x_triangle_perimeter
[1] 309.7428

$max_x_triangle_perimeter
[1] 2024.183

$range_x_triangle_perimeter
[1] 1741.031

$Q10_triangle_perimeter
[1] 525.6501

$Q20_triangle_perimeter
[1] 656.8388

$Q25_triangle_perimeter
[1] 701.4646

$Q30_triangle_perimeter
[1] 756.5406

$Q40_triangle_perimeter
[1] 855.9714

$Q60_triangle_perimeter
[1] 1051.601

$Q70_triangle_perimeter
[1] 1162.411

$Q75_triangle_perimeter
[1] 1240.914

$Q80_triangle_perimeter
[1] 1341.49

$Q90_triangle_perimeter
[1] 1643.694

$theil_index_triangle_perimeter
[1] 0.1631412

$gini_coeff_triangle_perimeter
[1] 0.2219247

In [23]:
print(graph_uni_lym)

$mean_x_weight
[1] 559.5647

$median_x_weight
[1] 572.86

$sd_x_weight
[1] 235.2004

$iqr_x_weight
[1] 339.0111

$skewness_x_weight
[1] 0.023169

$kurtosis_x_weight
[1] 1.915156

$min_x_weight
[1] 158.1078

$max_x_weight
[1] 972.42

$range_x_weight
[1] 818.1371

$Q10_weight
[1] 275.4948

$Q20_weight
[1] 341.8807

$Q25_weight
[1] 373.8321

$Q30_weight
[1] 442.7825

$Q40_weight
[1] 497.452

$Q60_weight
[1] 622.288

$Q70_weight
[1] 708.5934

$Q75_weight
[1] 737.991

$Q80_weight
[1] 769.6201

$Q90_weight
[1] 861.7075

$theil_index_weight
[1] 0.1517951

$gini_coeff_weight
[1] 0.2334459

$mean_x_closeness
[1] 0.001118417

$median_x_closeness
[1] 0.001090776

$sd_x_closeness
[1] 0.0002439847

$iqr_x_closeness
[1] 0.0003185355

$skewness_x_closeness
[1] 0.006142384

$kurtosis_x_closeness
[1] 1.959259

$min_x_closeness
[1] 0.0006956157

$max_x_closeness
[1] 0.001442123

$range_x_closeness
[1] 0.000704349

$Q10_closeness
[1] 0.000793602

$Q20_closeness
[1] 0.0009014683

$Q25_closeness
[1] 0.0009211277

$Q30_closeness
[1] 0.0009442703

$Q40_closeness
[1] 0.001029038

$Q60_closeness
[1] 0.001176152

$Q70_closeness
[1] 0.001274133

$Q75_closeness
[1] 0.001293406

$Q80_closeness
[1] 0.001301062

$Q90_closeness
[1] 0.001364034

$theil_index_closeness
[1] 0.1523647

$gini_coeff_closeness
[1] 0.1182617

$mean_x_betweenness
[1] 0.1013528

$median_x_betweenness
[1] 0.04756856

$sd_x_betweenness
[1] 0.1213526

$iqr_x_betweenness
[1] 0.1348485

$skewness_x_betweenness
[1] 0.971388

$kurtosis_x_betweenness
[1] 2.333333

$min_x_betweenness
[1] 0

$max_x_betweenness
[1] 0.3333333

$range_x_betweenness
[1] 0.3333333

$Q10_betweenness
[1] 0

$Q20_betweenness
[1] 0

$Q25_betweenness
[1] 0

$Q30_betweenness
[1] 0

$Q40_betweenness
[1] 0.01623377

$Q60_betweenness
[1] 0.08430769

$Q70_betweenness
[1] 0.1209091

$Q75_betweenness
[1] 0.1545455

$Q80_betweenness
[1] 0.1733333

$Q90_betweenness
[1] 0.2212121

$theil_index_betweenness
[1] 0.08945023

$gini_coeff_betweenness
[1] 0.6253289

$mean_x_degree
[1] 0.3528139

$median_x_degree
[1] 0.3452381

$sd_x_degree
[1] 0.1435012

$iqr_x_degree
[1] 0.1785714

$skewness_x_degree
[1] 0.07244707

$kurtosis_x_degree
[1] 2.104167

$min_x_degree
[1] 0.1666667

$max_x_degree
[1] 0.6041667

$range_x_degree
[1] 0.4201681

$Q10_degree
[1] 0.1787879

$Q20_degree
[1] 0.2535714

$Q25_degree
[1] 0.2613636

$Q30_degree
[1] 0.2792208

$Q40_degree
[1] 0.3090909

$Q60_degree
[1] 0.3909091

$Q70_degree
[1] 0.4279221

$Q75_degree
[1] 0.4545455

$Q80_degree
[1] 0.4545455

$Q90_degree
[1] 0.4916667

$theil_index_degree
[1] 0.05922949

$gini_coeff_degree
[1] 0.1839387

$mean_x_triangle_area
[1] 79444.65

$median_x_triangle_area
[1] 58704

$sd_x_triangle_area
[1] 54331.6

$iqr_x_triangle_area
[1] 52902.75

$skewness_x_triangle_area
[1] 0.7979994

$kurtosis_x_triangle_area
[1] 2.14107

$min_x_triangle_area
[1] 15640

$max_x_triangle_area
[1] 207540.5

$range_x_triangle_area
[1] 162110.5

$Q10_triangle_area
[1] 24372.8

$Q20_triangle_area
[1] 36250

$Q25_triangle_area
[1] 39309.5

$Q30_triangle_area
[1] 43956.9

$Q40_triangle_area
[1] 52201.5

$Q60_triangle_area
[1] 78532.5

$Q70_triangle_area
[1] 89436.4

$Q75_triangle_area
[1] 99501.5

$Q80_triangle_area
[1] 108968

$Q90_triangle_area
[1] 144252.3

$theil_index_triangle_area
[1] 0.2912646

$gini_coeff_triangle_area
[1] 0.3554519

$mean_x_triangle_perimeter
[1] 1550.505

$median_x_triangle_perimeter
[1] 1600.362

$sd_x_triangle_perimeter
[1] 454.2837

$iqr_x_triangle_perimeter
[1] 474.4855

$skewness_x_triangle_perimeter
[1] 0.053512

$kurtosis_x_triangle_perimeter
[1] 1.916976

$min_x_triangle_perimeter
[1] 1124.175

$max_x_triangle_perimeter
[1] 2296.585

$range_x_triangle_perimeter
[1] 1223.054

$Q10_triangle_perimeter
[1] 1154.362

$Q20_triangle_perimeter
[1] 1225.364

$Q25_triangle_perimeter
[1] 1315.593

$Q30_triangle_perimeter
[1] 1317.962

$Q40_triangle_perimeter
[1] 1417.131

$Q60_triangle_perimeter
[1] 1619.769

$Q70_triangle_perimeter
[1] 1768.688

$Q75_triangle_perimeter
[1] 1828.992

$Q80_triangle_perimeter
[1] 1887.92

$Q90_triangle_perimeter
[1] 2013.812

$theil_index_triangle_perimeter
[1] 0.1687758

$gini_coeff_triangle_perimeter
[1] 0.1391456

In [24]:
print(graph_uni_stroma)

$mean_x_weight
[1] 422.7649

$median_x_weight
[1] 410.4338

$sd_x_weight
[1] 203.9344

$iqr_x_weight
[1] 267.9188

$skewness_x_weight
[1] 0.432873

$kurtosis_x_weight
[1] 2.544082

$min_x_weight
[1] 34.67062

$max_x_weight
[1] 955.7179

$range_x_weight
[1] 911.2091

$Q10_weight
[1] 154.9787

$Q20_weight
[1] 240.6851

$Q25_weight
[1] 264.7611

$Q30_weight
[1] 299.9014

$Q40_weight
[1] 341.0211

$Q60_weight
[1] 463.1623

$Q70_weight
[1] 511.4983

$Q75_weight
[1] 548.3225

$Q80_weight
[1] 608.8998

$Q90_weight
[1] 715.8073

$theil_index_weight
[1] 0.1568586

$gini_coeff_weight
[1] 0.2862976

$mean_x_closeness
[1] 0.0009187695

$median_x_closeness
[1] 0.0008992776

$sd_x_closeness
[1] 0.0001521032

$iqr_x_closeness
[1] 0.0002304853

$skewness_x_closeness
[1] 0.1270672

$kurtosis_x_closeness
[1] 2.167736

$min_x_closeness
[1] 0.0006423851

$max_x_closeness
[1] 0.001214712

$range_x_closeness
[1] 0.0005478859

$Q10_closeness
[1] 0.0007467422

$Q20_closeness
[1] 0.0007881191

$Q25_closeness
[1] 0.0008071159

$Q30_closeness
[1] 0.0008183221

$Q40_closeness
[1] 0.0008439881

$Q60_closeness
[1] 0.0009576062

$Q70_closeness
[1] 0.0009991127

$Q75_closeness
[1] 0.001025823

$Q80_closeness
[1] 0.001069873

$Q90_closeness
[1] 0.001157488

$theil_index_closeness
[1] 0.1360779

$gini_coeff_closeness
[1] 0.09633413

$mean_x_betweenness
[1] 0.07060745

$median_x_betweenness
[1] 0.05324302

$sd_x_betweenness
[1] 0.06575749

$iqr_x_betweenness
[1] 0.09237145

$skewness_x_betweenness
[1] 0.8578098

$kurtosis_x_betweenness
[1] 2.854592

$min_x_betweenness
[1] 0

$max_x_betweenness
[1] 0.2260536

$range_x_betweenness
[1] 0.2260536

$Q10_betweenness
[1] 0.002886215

$Q20_betweenness
[1] 0.009359606

$Q25_betweenness
[1] 0.01432263

$Q30_betweenness
[1] 0.0187638

$Q40_betweenness
[1] 0.0343354

$Q60_betweenness
[1] 0.06650246

$Q70_betweenness
[1] 0.08825753

$Q75_betweenness
[1] 0.1090433

$Q80_betweenness
[1] 0.1195992

$Q90_betweenness
[1] 0.1545584

$theil_index_betweenness
[1] 0.2871469

$gini_coeff_betweenness
[1] 0.5073951

$mean_x_degree
[1] 0.1773399

$median_x_degree
[1] 0.1724138

$sd_x_degree
[1] 0.04911127

$iqr_x_degree
[1] 0.04695767

$skewness_x_degree
[1] 0.5986219

$kurtosis_x_degree
[1] 3.2255

$min_x_degree
[1] 0.08854167

$max_x_degree
[1] 0.2981481

$range_x_degree
[1] 0.1925926

$Q10_degree
[1] 0.1314655

$Q20_degree
[1] 0.1403941

$Q25_degree
[1] 0.1403941

$Q30_degree
[1] 0.1403941

$Q40_degree
[1] 0.1626437

$Q60_degree
[1] 0.1746684

$Q70_degree
[1] 0.1863426

$Q75_degree
[1] 0.1991379

$Q80_degree
[1] 0.2105911

$Q90_degree
[1] 0.2373563

$theil_index_degree
[1] 0.1203889

$gini_coeff_degree
[1] 0.1420874

$mean_x_triangle_area
[1] 57528.47

$median_x_triangle_area
[1] 41552.5

$sd_x_triangle_area
[1] 46589.97

$iqr_x_triangle_area
[1] 54435

$skewness_x_triangle_area
[1] 1.580801

$kurtosis_x_triangle_area
[1] 5.673442

$min_x_triangle_area
[1] 3094

$max_x_triangle_area
[1] 204343

$range_x_triangle_area
[1] 202385.5

$Q10_triangle_area
[1] 9644.825

$Q20_triangle_area
[1] 17034.7

$Q25_triangle_area
[1] 22690.31

$Q30_triangle_area
[1] 26537.03

$Q40_triangle_area
[1] 36178.9

$Q60_triangle_area
[1] 54400.25

$Q70_triangle_area
[1] 69668.1

$Q75_triangle_area
[1] 76960.75

$Q80_triangle_area
[1] 96632.55

$Q90_triangle_area
[1] 127438

$theil_index_triangle_area
[1] 0.3641266

$gini_coeff_triangle_area
[1] 0.4467777

$mean_x_triangle_perimeter
[1] 1246.634

$median_x_triangle_perimeter
[1] 1208.567

$sd_x_triangle_perimeter
[1] 420.2956

$iqr_x_triangle_perimeter
[1] 556.315

$skewness_x_triangle_perimeter
[1] 0.3815836

$kurtosis_x_triangle_perimeter
[1] 2.68617

$min_x_triangle_perimeter
[1] 377.4059

$max_x_triangle_perimeter
[1] 2094.82

$range_x_triangle_perimeter
[1] 1730.688

$Q10_triangle_perimeter
[1] 661.2278

$Q20_triangle_perimeter
[1] 835.1272

$Q25_triangle_perimeter
[1] 910.4946

$Q30_triangle_perimeter
[1] 982.411

$Q40_triangle_perimeter
[1] 1112.888

$Q60_triangle_perimeter
[1] 1348.421

$Q70_triangle_perimeter
[1] 1473.575

$Q75_triangle_perimeter
[1] 1581.644

$Q80_triangle_perimeter
[1] 1652.888

$Q90_triangle_perimeter
[1] 1803.35

$theil_index_triangle_perimeter
[1] 0.1553577

$gini_coeff_triangle_perimeter
[1] 0.2014317

In [25]:
print(graph_all)

  num_homotypic_edges num_heterotypic_edges graph_assortativity mean_degree_TC
1                98.5                 156.5        -0.005663561       5.638937
  mean_lcc_TC mean_degree_Lym mean_lcc_Lym mean_degree_Stroma mean_lcc_Stroma
1   0.4447567        5.531206    0.4565286             5.6325       0.4532165
  mean_degree_Others mean_lcc_Others avg_prop_TC_neighbor_for_TC
1           5.577381       0.4589363                   0.4335639
  avg_prop_Lym_neighbor_for_TC avg_prop_Stroma_neighbor_for_TC
1                   0.08363859                       0.3122982
  avg_prop_Others_neighbor_for_TC avg_prop_TC_neighbor_for_Lym
1                      0.09094651                    0.4532738
  avg_prop_Lym_neighbor_for_Lym avg_prop_Stroma_neighbor_for_Lym
1                    0.08273584                        0.3525794
  avg_prop_Others_neighbor_for_Lym avg_prop_TC_neighbor_for_Stroma
1                       0.08365286                       0.4181597
  avg_prop_Lym_neighbor_for_Stroma avg_prop_Stroma_neighbor_for_Stroma
1                       0.09413217                           0.3464766
  avg_prop_Others_neighbor_for_Stroma avg_prop_TC_neighbor_for_Others
1                          0.09051435                       0.4356656
  avg_prop_Lym_neighbor_for_Others avg_prop_Stroma_neighbor_for_Others
1                       0.08122294                            0.418835
  avg_prop_Others_neighbor_for_Others infiltration_score_TC_Lym
1                          0.06378968                  8.333333
  infiltration_score_TC_Stroma infiltration_score_TC_Others
1                     2.388715                         11.5
  infiltration_score_Lym_TC infiltration_score_Lym_Stroma
1                 0.4627783                     0.4494949
  infiltration_score_Lym_Others infiltration_score_Stroma_TC
1                             2                     1.317852
  infiltration_score_Stroma_Lym infiltration_score_Stroma_Others
1                           8.5                                9
  infiltration_score_Others_TC infiltration_score_Others_Lym
1                    0.4001536                           1.5
  infiltration_score_Others_Stroma mean_x_cross_weight median_x_cross_weight
1                        0.5388994            257.1352              231.4548
  sd_x_cross_weight iqr_x_cross_weight skewness_x_cross_weight
1          144.4707            158.072                1.429373
  kurtosis_x_cross_weight min_x_cross_weight max_x_cross_weight
1                5.891466           17.72005           889.8029
  range_x_cross_weight Q10_cross_weight Q20_cross_weight Q25_cross_weight
1             863.7312         87.11175         131.2741         150.1614
  Q30_cross_weight Q40_cross_weight Q60_cross_weight Q70_cross_weight
1         164.8282         190.1411            262.2         292.7087
  Q75_cross_weight Q80_cross_weight Q90_cross_weight theil_index_cross_weight
1         319.2488         344.8599         429.1093                0.1944182
  gini_coeff_cross_weight
1               0.3218815

## Entropy measurements

### Spatial Entropy using all cell types

In [26]:
spat_entropy_all = SpatialQPFs.spat_entropy_alltype(path = path, file = file, 
                                                    cell_class_var = "cell_id", 
                                                    x_var = "x", y_var = "y", scale = 200,
                                                    side_length = 2000, num_FOV = 10, set_seed = 42)

[1] 1
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 2
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 3
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 4
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 5
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 6
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 7
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 8
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 9
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done
[1] 10
Computing the pairwise distances for all observations. This may take some time...
All done
Computing the pairwise distances for all observations. This may take some time...
Done

In [27]:
print(spat_entropy_all)

$shannon
[1] 1.198687

$shannonZ_entropy
[1] 1.93634

$altieri_entropy_SMI
[1] 0.06840236

$altieri_entropy_RES
[1] 1.85931

$leibovici_entropy
[1] 2.27181

$spat_diversity
[1] 1.649454

### Spatial Entropy using one cell type

In [28]:
spat_entropy_TC = SpatialQPFs.spat_entropy_onetype(path = path, file = file, 
                                                   cell_class_var = "cell_id", 
                                                   x_var = "x", y_var = "y", 
                                                   cell_type = "TC", 
                                                   scale = 200)

In [29]:
print(spat_entropy_TC)

$batty_entropy
[1] -0.3319566

$battyLISA_entropy
[1] 6.262947

In [30]:
spat_entropy_Lym = SpatialQPFs.spat_entropy_onetype(path = path, file = file, 
                                                    cell_class_var = "cell_id", 
                                                    x_var = "x", y_var = "y", 
                                                    cell_type = "Lym", 
                                                    scale = 200)

In [31]:
print(spat_entropy_Lym)

$batty_entropy
[1] -1.285927

$battyLISA_entropy
[1] 5.580511

## Aggregating spatial feature outputs for downstream analysis

In [44]:
import pandas as pd
import rpy2.rinterface as ri
from rpy2.robjects import pandas2ri

def safe_r_to_pandas(r_object):
    """
    Safely converts an R object from rpy2 to a pandas DataFrame.

    Handles three cases:
    1. The R object is NULL (returns an empty DataFrame).
    2. The R object is already a pandas DataFrame (returns it directly).
    3. The R object is a standard R list/data.frame (converts it).

    Args:
        r_object: The object returned by an rpy2 call.

    Returns:
        A pandas DataFrame.
    """
    # Case 1: The R function returned NULL.
    if isinstance(r_object, ri.NULLType):
        print("Warning: R function returned NULL. Returning an empty DataFrame.")
        return pd.DataFrame()

    # Case 2: The object might have been auto-converted by rpy2 already.
    if isinstance(r_object, pd.DataFrame):
        return r_object

    # Case 3: The object is the expected R list/data.frame with a .names attribute.
    # Check if it has the 'names' attribute before proceeding.
    if hasattr(r_object, 'names'):
        # Your original, correct conversion logic
        df = pd.DataFrame({key: list(r_object.rx2(key)) for key in r_object.names})
        return df
    else:
        print(f"Warning: Received an unexpected R object of type {type(r_object)}. Returning an empty DataFrame.")
        return pd.DataFrame()

In [49]:
import pandas as pd
ss_point_uni_TC = safe_r_to_pandas(ss_point_uni_TC)
ss_point_uni_lym = safe_r_to_pandas(ss_point_uni_lym)
ss_point_bi = safe_r_to_pandas(ss_point_bi)
ss_point_ITLR = safe_r_to_pandas(ss_point_ITLR)
ss_lattice_bi = safe_r_to_pandas(ss_lattice_bi)
ss_geostat_bi = safe_r_to_pandas(ss_geostat_bi)
graph_uni_TC = safe_r_to_pandas(graph_uni_TC)
graph_uni_lym = safe_r_to_pandas(graph_uni_lym)
graph_uni_stroma = safe_r_to_pandas(graph_uni_stroma)
graph_all = safe_r_to_pandas(graph_all) 
spat_entropy_all = safe_r_to_pandas(spat_entropy_all)
spat_entropy_TC = safe_r_to_pandas(spat_entropy_TC)
spat_entropy_Lym = safe_r_to_pandas(spat_entropy_Lym)

if not ss_point_uni_TC.empty:
    ss_point_uni_TC.columns = ss_point_uni_TC.columns + '_TC'

if not ss_point_uni_lym.empty:
    ss_point_uni_lym.columns = ss_point_uni_lym.columns + '_Lym'

this_file = pd.DataFrame({"file":[file]})

In [52]:
frames = [this_file, ss_point_uni_TC, ss_point_uni_lym, ss_point_bi, ss_point_ITLR, ss_lattice_bi, ss_geostat_bi, graph_uni_TC, graph_uni_lym, graph_uni_stroma,
          graph_all, spat_entropy_all, spat_entropy_TC, spat_entropy_Lym]
this_res = pd.concat(frames, axis=1)
print(this_res)

      file  g_AUC_TC_TC_TC  g_r_TC_TC_TC  k_AUC_TC_TC_TC  k_vals_med_TC_TC_TC  \
0  dat.csv       -0.000034      0.044746        0.000007             0.002108

   k_vals_q1_TC_TC_TC  k_vals_q3_TC_TC_TC  k_vals_max_TC_TC_TC  \
0            0.000511            0.004734             0.008147

   pcf_AUC_TC_TC_TC  pcf_vals_med_TC_TC_TC  ...   shannon  shannonZ_entropy  \
0          0.002099               1.067271  ...  1.198687           1.93634

   altieri_entropy_SMI  altieri_entropy_RES  leibovici_entropy  \
0             0.068402              1.85931            2.27181

   spat_diversity  batty_entropy  battyLISA_entropy  batty_entropy  \
0        1.649454      -0.331957           6.262947      -1.285927

   battyLISA_entropy
0           5.580511

[1 rows x 622 columns]

In [53]:
this_res

,file,g_AUC_TC_TC_TC,g_r_TC_TC_TC,k_AUC_TC_TC_TC,k_vals_med_TC_TC_TC,k_vals_q1_TC_TC_TC,k_vals_q3_TC_TC_TC,k_vals_max_TC_TC_TC,pcf_AUC_TC_TC_TC,pcf_vals_med_TC_TC_TC,...,shannon,shannonZ_entropy,altieri_entropy_SMI,altieri_entropy_RES,leibovici_entropy,spat_diversity,batty_entropy,battyLISA_entropy,batty_entropy,battyLISA_entropy
0,dat.csv,-0.000034,0.044746,0.000007,0.002108,0.000511,0.004734,0.008147,0.002099,1.067271,...,1.198687,1.93634,0.068402,1.85931,2.27181,1.649454,-0.331957,6.262947,-1.285927,5.580511